name: mobile automation booking CI

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      device:
        description: |
          Enter device
          [Samsung Galaxy S9, Samsung Galaxy A23 5G, Google Pixel 5]
        required: true
        default: "Samsung Galaxy S9"

jobs:
  run-mobile-tests:
    runs-on: ubuntu-latest
    environment: SaucelabsTest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git identity
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Set timezone to Lima, Peru
        run: |
          sudo timedatectl set-timezone America/Lima
          date

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install dependencies
        run: mvn install -DskipTests
        env:
          SAUCE_USERNAME: ${{ vars.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ vars.SAUCE_ACCESS_KEY }}

      - name: Run cucumber tests
        run: mvn clean verify -Ddevice="${{ github.event.inputs.device }}"
        env:
          SAUCE_USERNAME: ${{ vars.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ vars.SAUCE_ACCESS_KEY }}

      - name: Upload cucumber Reports
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-reports
          path: target/cucumber-reports/

      - name: Clean up old reports in gh-pages branch (if exists)
        run: |
          if git ls-remote --heads https://github.com/${{ github.repository }} gh-pages; then
            git clone --depth=1 --branch=gh-pages https://github.com/${{ github.repository }} gh-pages
            rm -rf gh-pages/*
            git -C gh-pages add -A
            git -C gh-pages commit -am "Remove old reports"
            git -C gh-pages push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
          else
            echo "La rama gh-pages no existe, se omite la limpieza."
          fi

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/cucumber-reports/cucumber-html-reports
          publish_branch: gh-pages

      - name: Show GitHub Pages URL Summary
        run: |
          echo "Your GitHub Pages site is live at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/overview-features.html"